name: VitalEnchant
version: @version@
main: com.tamrielnetwork.vitalenchant.VitalEnchant
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Gives players the ability to enchant items.
commands:
  vitalenchant:
    description: "Main command"
    usage: "/vitalenchant"
permissions:
  vitalenchant.enchant:
    description: "Permission to enchant items"
    default: op